
#
# Makefile for lab 6, part 1
#

CC  = gcc
CXX = g++

INCLUDES = 
CFLAGS   = -g -Wall $(INCLUDES)
CXXFLAGS = -g -Wall $(INCLUDES)

LDFLAGS = -g 
LDLIBS = 

.PHONY: default
default: http-server

# header dependency


.PHONY: clean
clean:
	rm -f *.o *~ a.out core http-server 

.PHONY: all
all: clean default

