CC  = gcc

INCLUDES = -I../../../lab3/solutions/part1
CFLAGS   = -g -Wall $(INCLUDES)

LDFLAGS = -g -L../../../lab3/solutions/part1
LDLIBS = -lmylist

mdb-lookup:

.PHONY: clean
clean:
	rm -f *.o mdb-lookup 

.PHONY: all
all: clean 

