CC  = gcc

INCLUDES = 
CFLAGS   = -g -Wall $(INCLUDES)

LDFLAGS = -g 
LDLIBS = 

mdb-lookup-server-nc-1:

mdb-lookup-server-nc-2:

.PHONY: clean
clean:
	rm -f *.o mdb-lookup-server-nc-1 mdb-lookup-server-nc-2

.PHONY: all
all: clean

