CC  = gcc

INCLUDES = -I../../lab3/solutions/part1
CFLAGS   = -g -Wall $(INCLUDES)

LDFLAGS = -g -L../../lab3/solutions/part1
LDLIBS = -lmylist

mdb-lookup:

mdb-add:

.PHONY: clean
clean:
	rm -f *.o mdb-lookup mdb-add 

.PHONY: all
all: clean 

